### ISSUE TITLE
Extension crashing when clicking on "offline" job

### ISSUE THREAD

**Issue by lazyfrosch** [AdamNowotny/BuildReactor#15]
I noticed that the whole extension crashes when I click on a offline job.

Offline jobs happen for me when either I'm logged out of Jenkins, or it is a multi-branch job.

After the crash the extension is show as corrupted, only offering me a repair, luckily I can just re-enable it with the "Apps & Extensions developer tool".

```
Fontconfig error: Cannot load default config file
[7453:7484:0312/092550:ERROR:channel.cc(305)] RawChannel read error (connection broken)
```

From `chrome_debug.log`

```
[7453:7453:0312/092858:INFO:CONSOLE(31555)] "2015-03-12T08:28:58.060Z", source: chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common-ui/main.js (31555)
[7453:7453:0312/092858:INFO:CONSOLE(31563)] "2015-03-12T08:28:58.065Z", source: chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common-ui/main.js (31563)
[7453:7453:0312/092858:INFO:CONSOLE(31571)] "2015-03-12T08:28:58.066Z", source: chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common-ui/main.js (31571)
[7453:7453:0312/092858:INFO:CONSOLE(0)] "Unchecked runtime.lastError while running tabs.get: No tab with id: 96.
    at Object.event.invoke (chrome-extension://ompiailgknfdndiefoaoiligalphfdae/background/event.js:46:14)
    at chrome-extension://ompiailgknfdndiefoaoiligalphfdae/background/init.js:29:10", source: chrome-extension://ompiailgknfdndiefoaoiligalphfdae/_generated_background_page.html (0)
[7453:7453:0312/092858:INFO:CONSOLE(0)] "Unchecked runtime.lastError while running tabs.get: No tab with id: 96.
    at chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/background.js:1275:23", source: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/_generated_background_page.html (0)
[7453:7453:0312/092858:INFO:CONSOLE(0)] "Unchecked runtime.lastError while running browserAction.setBadgeText: No tab with id: 96.
    at Object.WebDeveloper.Storage.updateBadgeText (chrome-extension://bfbameneiokkgbdmiekhjnmfkcnldhhm/storage/storage.js:169:24)
    at WebDeveloper.Storage.tabSelectionChanged (chrome-extension://bfbameneiokkgbdmiekhjnmfkcnldhhm/storage/storage.js:87:24)", source: chrome-extension://bfbameneiokkgbdmiekhjnmfkcnldhhm/background/background.html (0)
[7453:7453:0312/092858:INFO:CONSOLE(0)] "Unchecked runtime.lastError while running browserAction.setTitle: No tab with id: 96.
    at Object.WebDeveloper.Storage.updateBadgeText (chrome-extension://bfbameneiokkgbdmiekhjnmfkcnldhhm/storage/storage.js:170:24)
    at WebDeveloper.Storage.tabSelectionChanged (chrome-extension://bfbameneiokkgbdmiekhjnmfkcnldhhm/storage/storage.js:87:24)", source: chrome-extension://bfbameneiokkgbdmiekhjnmfkcnldhhm/background/background.html (0)
[7453:7453:0312/092858:INFO:CONSOLE(0)] "Unchecked runtime.lastError while running tabs.get: No tab with id: 96.
    at chrome-extension://ompiailgknfdndiefoaoiligalphfdae/background/init.js:56:14", source: chrome-extension://ompiailgknfdndiefoaoiligalphfdae/_generated_background_page.html (0)
[7453:7453:0312/092858:INFO:CONSOLE(0)] "Unchecked runtime.lastError while running tabs.get: No tab with id: 96.
    at requestDomain (chrome-extension://dbpojpfdiliekbbiplijcphappgcgjfn/js/background.js:1:2773)
    at chrome-extension://dbpojpfdiliekbbiplijcphappgcgjfn/js/background.js:1:3146", source: chrome-extension://dbpojpfdiliekbbiplijcphappgcgjfn/background.html (0)
```

`chrome_debug.log` with all other extensions disabled:

```
[7453:7453:0312/093130:INFO:CONSOLE(31555)] "2015-03-12T08:31:30.495Z", source: chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common-ui/main.js (31555)
[7453:7453:0312/093130:INFO:CONSOLE(31563)] "2015-03-12T08:31:30.521Z", source: chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common-ui/main.js (31563)
[7453:7453:0312/093130:INFO:CONSOLE(31571)] "2015-03-12T08:31:30.523Z", source: chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common-ui/main.js (31571)
[7453:7484:0312/093131:ERROR:channel.cc(305)] RawChannel read error (connection broken)
```

I'd be happy to support any other detail.

**Comment by AdamNowotny** [comment]
I saw it happening earlier but seems to not crash anymore in latest Chrome, as least on Linux.
What system do you use?
Would be useful to see what is the href generated, can you look in the source for one of the builds? Something like:
```
<a href="" target="_blank" class="progress-bar" ng-class="{ 'active': build.isRunning, 'progress-bar-striped':build.isRunning }">
[...]
	</a>
```
There is definitely a problem with use of src attribute with angular expression but I wonder if it's enough to make the href empty or "#" or do I need to remove the link in that case completely.

**Comment by AdamNowotny** [comment]
Just pushed some changes (just to git) to deactivate link when webUrl is empty which is probably the case for offline builds. You can give it a go to see if it still crashes.

**Comment by lazyfrosch** [comment]
Thats the button code, I try to use a snapshot and come back to you.

```
<build class="group-items ng-scope ng-isolate-scope" build-info="item" ng-repeat="item in items" ng-style="{ width: itemWidth }" style="width: 50%;"><div class="build offline" ng-class="{ 'broken': build.isBroken, 'disabled': build.isDisabled, 'building': build.isRunning, 'offline': build.error }">
	<a href="" target="_blank" class="progress-bar" ng-class="{ 'active': build.isRunning, 'progress-bar-striped':build.isRunning }">
		<span class="labels pull-right">
			<span ng-show="build.error" class="label label-default ng-scope" tooltip="Not Found">
				Offline	<span class="error-message ng-binding">(Not Found)</span>
			</span>
			<!-- ngRepeat: tag in build.tags -->
			<span ng-show="build.isDisabled" class="label label-default ng-hide">Disabled</span>
		</span>
		<span class="build-name ng-binding">Lazyfrosch.de Puppet Environment</span>
	</a>
</div></build>
```

**Comment by lazyfrosch** [comment]
Yep it does not crash anymore with current master, thanks a lot!
