### ISSUE TITLE
Build shown as Offline

### ISSUE THREAD

**Issue by Graham42** [AdamNowotny/BuildReactor#21]
Some bulds are showing up as 'Offline' and the tooltip seems to have an error message.

![broffline](https://cloud.githubusercontent.com/assets/2476733/7597847/54ab1bdc-f8c4-11e4-8ec9-66628095f761.png)

**Comment by AdamNowotny** [comment]
Most likely it's not the tooltip problem but parsing problem. I'd need to know a bit more - what CI server are you using?
Also there is probably more information about the error in the background page console.

**Comment by Graham42** [comment]
Right, should have thought to check the console. Here's the error message
```javascript
"error": {
    "name": "TypeError",
    "message": "Cannot read property 'split' of undefined",
    "description": "Cannot read property 'split' of undefined",
    "stack": 
// formatted...
"
TypeError: Cannot read property 'split' of undefined
    at chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/core/main.js:1669:30
    at Array.map (native)
    at AnonymousObservable.<anonymous> (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/core/main.js:1666:52)
    at next (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:12724:34)
    at AnonymousObserver._onNext (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:12749:13)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:11488:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:11417:22)
    at AutoDetachObserverPrototype.next (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:13887:31)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:11417:22)
    at AnonymousObserver._onNext (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:12528:22)
"
}
```

**Comment by ragol** [comment]
Have the same problem with Jenkins for a few days (a week at most). It worked flawlessly before that.

**Comment by Graham42** [comment]
Debugged and found the issue. I will say, Chrome plugin development has certainly improved with the dev tools for plugins/extenions: https://chrome.google.com/webstore/detail/chrome-apps-extensions-de/ohmmkhmmmpcnpikjeljgnaoabkaalbgc

**Comment by cobrabr** [comment]
A similar problem is happening with some of my Jenkins builds, except the error message is `Cannot read property 'map' of undefined`. Other builds work properly, so it isn't a Jenkins version compatibility issue.

I tried opening the console while checking the Dashboard, but no error shows in there.

**Comment by Graham42** [comment]
@cobrabr please open a new issue, this one has been fixed for a long time and is not related

**Comment by cobrabr** [comment]
Will do.
