### ISSUE TITLE
Jenkins Workflow jobs are offline (Cannot read property 'items' of undefined)

### ISSUE THREAD

**Issue by christofferholmstedt** [AdamNowotny/BuildReactor#41]
I've just installed and configured BuildReactor for a local Jenkins server. I've configured BuildReactor to monitor 6 projects, 4 Freestyle projects and 2 Jenkins Workflow projects. The 4 freestyle projects works just fine and shows up in BuildReactor but the two projects configured with Jenkins Workflow (https://wiki.jenkins-ci.org/display/JENKINS/Workflow+Plugin) are "Offline" due to problem below.

```
stack: "TypeError: Cannot read property 'items' of undefined
at AnonymousObservable.<anonymous> (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/core/main.js:1726:45)
at next (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:13044:34)
at AnonymousObserver._onNext (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:13069:13)
at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:11565:12)
at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:11497:35)
at AutoDetachObserverPrototype.next (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:14234:23)
at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:11497:35)
at AnonymousObserver._onNext (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:12785:80)
at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:11565:12)
at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (chrome-extension://agfdekbncfakhgofmaacjfkpbhjhpjmp/src/common/main.js:11497:35)"
```
Any more information that I can give to help find/solve this issue?

**Comment by AdamNowotny** [comment]
Most likely a problem in this line: https://github.com/AdamNowotny/BuildReactor/blob/master/src/core/services/jenkins/jenkinsBuild.js#L26

Is the "changeSet" element in the response from ```http://server/job/[job_id]/lastCompletedBuild/api/json``` ?

**Comment by christofferholmstedt** [comment]
Nope, I never get any "changeSet" in singular for workflow projects. It is always "changeSets" in plural, even if there is no change.

Here are some examples:
```
"changeSets": [{
	"items": [],
	"kind": "svn",
	"revisions": [{
		"module": "<snip url>",
		"revision": 1234
	}]
}],
```
```
"changeSets": [{
		"items": [{
			"affectedPaths": ["<snip>"],
			"author": {
				"absoluteUrl": "<snip>",
				"fullName": "<snip>"
			},
			"commitId": "1235",
			"timestamp": 1448544628405,
			"date": "2015-11-26T13:30:28.405995Z",
			"msg": "<snip>",
			"paths": [{
				"editType": "edit",
				"file": "<snip>"
			}],
			"revision": 1235,
			"user": "<snip>"
		},
		{
			"affectedPaths": ["<snip>"],
			"author": {
				"absoluteUrl": "<snip>",
				"fullName": "<snip>"
			},
			"commitId": "1234",
			"timestamp": 1448543949992,
			"date": "2015-11-26T13:19:09.992576Z",
			"msg": "<snip>",
			"paths": [{
				"editType": "edit",
				"file": "<snip>"
			}],
			"revision": 1234,
			"user": "<snip>"
		},
		{
			"affectedPaths": ["<snip>"],
			"author": {
				"absoluteUrl": "<snip>",
				"fullName": "<snip>"
			},
			"commitId": "1233",
			"timestamp": 1448543671961,
			"date": "2015-11-26T13:14:31.961090Z",
			"msg": "<snip>",
			"paths": [{
				"editType": "edit",
				"file": "<snip>"
			}],
			"revision": 1233,
			"user": "<snip>"
		},
		{
			"affectedPaths": ["<snip>"],
			"author": {
				"absoluteUrl": "<snip>",
				"fullName": "<snip>"
			},
			"commitId": "1226",
			"timestamp": 1448460299470,
			"date": "2015-11-25T14:04:59.470648Z",
			"msg": "<snip>",
			"paths": [{
				"editType": "edit",
				"file": "<snip>"
			}],
			"revision": 1226,
			"user": "<snip>"
		},
		{
			"affectedPaths": ["<snip>"],
			"author": {
				"absoluteUrl": "<snip>",
				"fullName": "<snip>"
			},
			"commitId": "1223",
			"timestamp": 1448455693827,
			"date": "2015-11-25T12:48:13.827391Z",
			"msg": "<snip>",
			"paths": [{
				"editType": "edit",
				"file": "<snip>"
			}],
			"revision": 1223,
			"user": "<snip>"
		}],
		"kind": "svn",
		"revisions": [{
			"module": "<snip>",
			"revision": 3848
		}]
	},
	{
		"items": [],
		"kind": "svn",
		"revisions": [{
			"module": "<snip>",
			"revision": 2448
		}]
	},
	{
		"items": [],
		"kind": "svn",
		"revisions": [{
			"module": "<snip>",
			"revision": 2448
		}]
	},
	{
		"items": [],
		"kind": "svn",
		"revisions": [{
			"module": "<snip>",
			"revision": 2448
		}]
	}],
```
```
"changeSets": [{
		"items": [],
		"kind": "svn",
		"revisions": [{
			"module": "<snip>",
			"revision": 2448
		}]
	},
	{
		"items": [],
		"kind": "svn",
		"revisions": [{
			"module": "<snip>",
			"revision": 2448
		}]
	},
	{
		"items": [],
		"kind": "svn",
		"revisions": [{
			"module": "<snip>",
			"revision": 2448
		}]
	},
	{
		"items": [],
		"kind": "svn",
		"revisions": [{
			"module": "<snip>",
			"revision": 2448
		}]
	}],
````

**Comment by AdamNowotny** [comment]
Added the example to
https://github.com/AdamNowotny/BuildReactor/blob/master/src/core/services/jenkins/lastCompletedBuild-workflow.fixture.json
The parsing code is here:
https://github.com/AdamNowotny/BuildReactor/blob/master/src/core/services/jenkins/jenkinsBuild.js

So far the only element was "changeSet", like in https://ci.jenkins-ci.org/job/infra_backend-merge-all-repo/lastCompletedBuild/api/json
but seems like it's it's different for workflow projects.
The changes from all changesets should be parsed now.
Will publish this soon, but feel free to build from git.

**Comment by christofferholmstedt** [comment]
Thanks for the update.
