### ISSUE TITLE
Get a TypeError when running the latest code locally

### ISSUE THREAD

**Issue by provshayne** [AdamNowotny/BuildReactor#59]
After cloning the repo, running npm install, npm run dist and then adding the extension in Chrome. I set up my TeamCity config and click save and get nothing. While looking at in inspector I see 

commons.js:35552 TypeError: Cannot read property 'error' of undefined
    at settings.js:1210
    at ChildScope.$eval (commons.js:39314)
    at Scope.$digest (commons.js:39127)
    at commons.js:39353
    at completeOutstandingRequest (commons.js:27596)
    at commons.js:27875

![screen shot 2016-10-27 at 2 40 59 pm](https://cloud.githubusercontent.com/assets/1307551/19786622/bd441a48-9c53-11e6-8c4d-6124106fab85.png)

**Comment by AdamNowotny** [comment]
The response is undefined so there must be an error in the background page. You can open it on the extensions page or get the latest code (with this commit from few hours ago https://github.com/AdamNowotny/BuildReactor/commit/f388942d272fcf6ce2f80a51e7d30cc85b1c5aca) which should show the errors in the console on any of the angular pages as well.

**Comment by provshayne** [comment]
Alright. I was finally able to capture the error in the background.

"TypeError: Cannot read property 'baseUrl' of null
    at availableProjects (chrome-extension://kkhdfpjajdncbdokhplkmamfmaindmbf/1.chunk.js:12129:67)
    at onMessageHandler (chrome-extension://kkhdfpjajdncbdokhplkmamfmaindmbf/1.chunk.js:12083:5)
    at onMessage (chrome-extension://kkhdfpjajdncbdokhplkmamfmaindmbf/1.chunk.js:12066:4)
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:151:26)
    at EventImpl.dispatch_ (extensions::event_bindings:372:35)
    at EventImpl.dispatch (extensions::event_bindings:394:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:151:26)
    at messageListener (extensions::messaging:207:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)"

**Comment by provshayne** [comment]
Now I'm getting this error when trying to save a configuration. 

"TypeError: Cannot read property 'map' of undefined
    at Object.saveService (chrome-extension://kkhdfpjajdncbdokhplkmamfmaindmbf/1.chunk.js:11141:51)
    at onMessageHandler (chrome-extension://kkhdfpjajdncbdokhplkmamfmaindmbf/1.chunk.js:12104:36)
    at onMessage (chrome-extension://kkhdfpjajdncbdokhplkmamfmaindmbf/1.chunk.js:12066:4)
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:151:26)
    at EventImpl.dispatch_ (extensions::event_bindings:372:35)
    at EventImpl.dispatch (extensions::event_bindings:394:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:151:26)
    at messageListener (extensions::messaging:207:29)
    at EventImpl.dispatchToListener (extensions::event_bindings:388:22)"

**Comment by AdamNowotny** [comment]
Good catch, there is a problem when local store has never been initialized before. For now you might try going to configuration tab and saving "[]" (empty array) as config.

**Comment by AdamNowotny** [comment]
Actually seems like the problem was somewhere else. Can you pull latest code and see if same problem happens? "availableProjects" should not return undefined.
